[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "cd server",
  "cp package.production.json package.json",
  "npm install --only=production"
]

[phases.build]
cmds = [
  "echo 'Build phase complete'"
]

[start]
cmd = "cd server && node start.js"
